### ISSUE TITLE
Error: ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

### ISSUE THREAD

**Issue by FoldZero** [FabianSchurig/CustomScrews#11]
Im getting an error today running the addin. Just did Fusion latest update today also. 

> ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

Manageed to resolved by manually installing 

`C:\Users\%USERNAME%\AppData\Roaming\Autodesk\Autodesk Fusion 360\API\AddIns\CustomScrews> pip install urllib3 -t ./modules/ --upgrade`

/modules/
![image](https://github.com/user-attachments/assets/e73a79af-9ded-475f-950f-e06e475c3186)

Restarted Fusion and all is well.

**Comment by TheArtizan** [comment]
I have a similar issue - I am using a Mac running Sonoma. I have installed Python3 to see if this fixed it - tried restarting computer a few times but still get the following message in the "TEXT COMMANDS " at the bottom of Fusion 

[ SCRIPT ERROR 

Traceback (most recent call last):
  
File "/Users/xxxxx/Library/Containers/com.autodesk.mas.fusion360/Data/Library/Application Support/Autodesk/ApplicationPlugins/CustomScrews.bundle/Contents/CustomScrews.py", line 17, in <module>
    import requests
  
File "/Users/xxxxx/Library/Containers/com.autodesk.mas.fusion360/Data/Library/Application Support/Autodesk/ApplicationPlugins/CustomScrews.bundle/Contents/modules/requests/__init__.py", line 43, in <module>
    import urllib3
  
File "/Users/xxxxx/Library/Containers/com.autodesk.mas.fusion360/Data/Library/Application Support/Autodesk/ApplicationPlugins/CustomScrews.bundle/Contents/modules/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import 
  
File "/Users/xxxxx/Library/Containers/com.autodesk.mas.fusion360/Data/Library/Application Support/Autodesk/ApplicationPlugins/CustomScrews.bundle/Contents/modules/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import 

File "/Users/xxxxx/Library/Containers/com.autodesk.mas.fusion360/Data/Library/Application Support/Autodesk/ApplicationPlugins/CustomScrews.bundle/Contents/modules/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import 
(ModuleNotFoundError: No module named 'urllib3.packages.six.moves '] 

- not sure what else to try at the moment -

**Comment by kqkq** [comment]
same issue for me.
macOS 15.1.1

**Comment by FabianSchurig** [comment]
I just removed the module requests from the dependencies. Instead I add config.json which has all the presets for the screws. There is also a way to add new screws in additional json files locally. I did not test it 100% yet but it at least starts.

(Version 1.4.0)

- [x] Need to test the Add-In functionality
- [x] Upload the Add-In to the App store.

**Comment by FabianSchurig** [comment]
I uploaded the release zip file https://github.com/FabianSchurig/CustomScrews/releases/tag/v1.4.0 to the Autodesk Add-In center as submission. It will soon be released. If you notice any problems, please let me know.

Thanks!
